const propiedades = [
    {
        id: 1,
        titulo: "Casa Moderna en Cholula",
        precio: 2500000,
        ubicacion: "Cholula, Puebla",
        m2: 180,
        recamaras: 3,
        banos: 2.5,
        tipo: "Casa",
        imagen: "img/propiedades/propiedad1.jpg",
        destacado: true
    },
    {
        id: 2,
        titulo: "Departamento de Lujo Angelópolis",
        precio: 3200000,
        ubicacion: "Angelópolis, Puebla",
        m2: 120,
        recamaras: 2,
        banos: 2,
        tipo: "Departamento",
        imagen: "img/propiedades/propiedad2.jpg",
        destacado: false
    },
    {
        id: 3,
        titulo: "Terreno Residencial Lomas",
        precio: 1500000,
        ubicacion: "Lomas de Angelópolis",
        m2: 200,
        recamaras: 0,
        banos: 0,
        tipo: "Terreno",
        imagen: "img/propiedades/propiedad3.jpg",
        destacado: true
    },
    {
        id: 4,
        titulo: "Loft Industrial Centro",
        precio: 1800000,
        ubicacion: "Centro Histórico",
        m2: 90,
        recamaras: 1,
        banos: 1,
        tipo: "Departamento",
        imagen: "img/propiedades/propiedad4.jpg",
        destacado: false
    },
    {
        id: 5,
        titulo: "Casa Familiar en Forjadores",
        precio: 2100000,
        ubicacion: "Cuautlancingo",
        m2: 150,
        recamaras: 3,
        banos: 2,
        tipo: "Casa",
        imagen: "img/propiedades/propiedad5.jpg",
        destacado: false
    },
    {
        id: 6,
        titulo: "Penthouse Vista Panorámica",
        precio: 4500000,
        ubicacion: "La Paz, Puebla",
        m2: 210,
        recamaras: 3,
        banos: 3,
        tipo: "Departamento",
        imagen: "img/propiedades/propiedad6.jpg",
        destacado: true
    },
    {
        id: 7,
        titulo: "Casa con Jardín Amplio",
        precio: 2800000,
        ubicacion: "Momoxpan",
        m2: 200,
        recamaras: 4,
        banos: 3,
        tipo: "Casa",
        imagen: "img/propiedades/propiedad7.jpg",
        destacado: false
    },
    {
        id: 8,
        titulo: "Terreno Comercial Atlixcayotl",
        precio: 5000000,
        ubicacion: "Atlixcayotl",
        m2: 300,
        recamaras: 0,
        banos: 0,
        tipo: "Terreno",
        imagen: "img/propiedades/propiedad8.jpg",
        destacado: true
    },
    {
        id: 9,
        titulo: "Departamento Estudiantes",
        precio: 1200000,
        ubicacion: "CU BUAP",
        m2: 65,
        recamaras: 2,
        banos: 1,
        tipo: "Departamento",
        imagen: "img/propiedades/propiedad9.jpg",
        destacado: false
    },
    {
        id: 10,
        titulo: "Residencia de Lujo Zavaleta",
        precio: 6200000,
        ubicacion: "Zavaleta",
        m2: 350,
        recamaras: 4,
        banos: 4.5,
        tipo: "Casa",
        imagen: "img/propiedades/propiedad10.jpg",
        destacado: true
    },
    {
        id: 11,
        titulo: "Casa Colonial Centro",
        precio: 3500000,
        ubicacion: "Puebla Centro",
        m2: 280,
        recamaras: 5,
        banos: 3,
        tipo: "Casa",
        imagen: "img/propiedades/propiedad11.jpg",
        destacado: false
    },
    {
        id: 12,
        titulo: "Terreno en Haras",
        precio: 950000,
        ubicacion: "Haras del Bosque",
        m2: 500,
        recamaras: 0,
        banos: 0,
        tipo: "Terreno",
        imagen: "img/propiedades/propiedad12.jpg",
        destacado: true
    },
];